### ISSUE TITLE
import { useHistory } from 'react-router-dom';

### ISSUE THREAD

**Issue by fedot199614** [kwameopareasiedu/react-simple-widgets#13]
./node_modules/react-simple-widgets/dist/use-query-params.js
[1] Attempted import error: 'useNavigate' is not exported from 'react-router-dom' (imported as 'o').

**Comment by kwameopareasiedu** [comment]
U need to update your project's `react-router-dom` to at least `v6` which contains the `useNavigate` hook...

**Comment by kwameopareasiedu** [comment]
I'm closing this issue because this is most certainly a version mismatch in your `package.json`. Feel free to reopen if otherwise
